import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Eternal Flame Ring',
    slug: 'eternal-flame-ring',
    category: 'Rings',
    price: 350000,
    description: 'A magnificent 24k gold ring featuring a timeless design that symbolizes eternal love. The central diamond is cradled by intricate gold work, creating a piece of unparalleled beauty.',
    images: ['https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1470&auto=format&fit=crop', 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=1480&auto=format&fit=crop', 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1470&auto=format&fit=crop'],
    metalType: '24k Gold',
    featured: true,
  },
  {
    id: '2',
    name: 'Multani Heritage Necklace',
    slug: 'multani-heritage-necklace',
    category: 'Necklaces',
    price: 950000,
    description: 'Inspired by the rich heritage of Multan, this 22k gold necklace is a masterpiece of traditional craftsmanship. Adorned with rubies and pearls, it is a statement of regal elegance.',
    images: ['https://storage.googleapis.com/aif-stg-testing-public-file-upload/users/20133658/1721758414451-image.jpeg', 'https://placehold.co/800x800/000000/FFFFFF?text=Necklace'],
    metalType: '22k Gold',
    featured: true,
  },
  {
    id: '3',
    name: 'Celestial Link Bracelet',
    slug: 'celestial-link-bracelet',
    category: 'Bracelets',
    price: 250000,
    description: 'A delicate white gold bracelet with interlocking circles, representing an unbreakable bond. Each link is studded with micro-diamonds for a subtle, sophisticated sparkle.',
    images: ['https://images.unsplash.com/photo-1611652022419-a9419f74343d?q=80&w=1374&auto=format&fit=crop'],
    metalType: 'White Gold',
    featured: true,
  },
  {
    id: '4',
    name: 'Rose Petal Earrings',
    slug: 'rose-petal-earrings',
    category: 'Earrings',
    price: 180000,
    description: 'Elegant rose gold earrings designed to mimic the delicate form of a blooming rose. These earrings are perfect for adding a touch of romance to any ensemble.',
    images: ['https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=1587&auto=format&fit=crop'],
    metalType: 'Rose Gold',
    featured: true,
  },
  {
    id: '5',
    name: 'Sultanate Signet Ring',
    slug: 'sultanate-signet-ring',
    category: 'Rings',
    price: 450000,
    description: 'A bold and masculine 24k gold signet ring, reminiscent of the power and prestige of ancient sultans. Perfect for the modern man who appreciates history and style.',
    images: ['https://images.unsplash.com/photo-1586104195538-050b9f74f58e?q=80&w=1480&auto=format&fit=crop'],
    metalType: '24k Gold',
  },
  {
    id: '6',
    name: 'Indus River Necklace',
    slug: 'indus-river-necklace',
    category: 'Necklaces',
    price: 800000,
    description: 'A flowing, artistic 22k gold necklace that captures the fluid beauty of the Indus River. Embellished with sapphires that mirror the water\'s depths.',
    images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1587&auto=format&fit=crop'],
    metalType: '22k Gold',
  },
   {
    id: '7',
    name: 'Peacock Throne Bracelet',
    slug: 'peacock-throne-bracelet',
    category: 'Bracelets',
    price: 550000,
    description: 'An opulent 22k gold cuff bracelet inspired by the legendary Peacock Throne. Features intricate enamel work and a central emerald.',
    images: ['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=1480&auto=format&fit=crop'],
    metalType: '22k Gold',
    featured: true,
  },
  {
    id: '8',
    name: 'Starlight Stud Earrings',
    slug: 'starlight-stud-earrings',
    category: 'Earrings',
    price: 120000,
    description: 'Simple yet stunning, these white gold stud earrings feature a single, brilliant-cut diamond, like a star in the night sky.',
    images: ['https://images.unsplash.com/photo-1589128777073-263566ae5e4d?q=80&w=1587&auto=format&fit=crop'],
    metalType: 'White Gold',
  },
];

export const featuredProducts = products.filter(p => p.featured);
